export const LOADING = 'LOADING';
export const SET_RESULTS_PER_PAGE = 'SET_RESULTS_PER_PAGE';
export const SAVE_SEARCH_RESULTS = 'SAVE_SEARCH_RESULTS';
export const SAVE_ARTIST_RESULTS = 'SAVE_ARTIST_RESULTS';
export const SAVE_TITLE_RESULTS = 'SAVE_TITLE_RESULTS';
export const INVALIDATE_CACHE = 'INVALIDATE_CACHE';